@echo off
rem Copy this file to start_api.local.bat and replace the placeholders.
set "GROQ_API_KEY=PASTE_YOUR_GROQ_API_KEY_HERE"
set "LANGSMITH_API_KEY=PASTE_YOUR_LANGSMITH_API_KEY_HERE"
set "NOTION_TOKEN=PASTE_YOUR_NOTION_INTEGRATION_TOKEN_HERE"
set "NOTION_DATABASE_ID=PASTE_YOUR_NOTION_DATABASE_ID_HERE"
